services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookify_app
    volumes:
      - .:/var/www/html
      - composer_cache:/tmp/composer
    env_file:
      - .env
    environment:
      # nginx-proxy configuration
      VIRTUAL_HOST: ${VIRTUAL_HOST:-bookify.test}
      VIRTUAL_PORT: 81
      # Let's Encrypt configuration (only in production)
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST:-}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-}
    depends_on:
      db:
        condition: service_healthy
    user: root
    command: >
      sh -c "
        chown -R www-data:www-data /var/www/html &&
        chmod -R 755 /var/www/html &&
        su -s /bin/sh www-data -c 'composer install --no-interaction' &&
        if grep -q '^APP_KEY=$$' .env || [ -z \"$$(grep '^APP_KEY=' .env | cut -d '=' -f2)\" ]; then
          echo 'ðŸ”‘ APP_KEY is empty â€” generating new key...';
          php artisan key:generate;
        else
          echo 'âœ… APP_KEY already set, skipping key:generate';
        fi &&
        su -s /bin/sh www-data -c 'php artisan migrate --force' &&
        exec php-fpm -F
      "
    restart: unless-stopped
    networks:
      - nginx-proxy
      - bookify_network

  web:
    image: nginx:alpine
    container_name: bookify_web
    restart: unless-stopped
    ports:
      - "81:81"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx-external.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - nginx-proxy
      - bookify_network
    environment:
      # nginx-proxy configuration
      VIRTUAL_HOST: ${VIRTUAL_HOST:}
      VIRTUAL_PORT: 81
      # Let's Encrypt configuration (only in production)
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

  db:
    image: mysql:9.5
    container_name: bookify_mysql
    restart: unless-stopped
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: "Hisham!0675AIT"
    volumes:
      - bookify_db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 5
      timeout: 5s
    networks:
      - bookify_network

networks:
  nginx-proxy:
    external: true
  bookify_network:
    driver: bridge

volumes:
  bookify_db:
  composer_cache:

